### ISSUE TITLE
Any demos in Swift?

### ISSUE THREAD

**Issue by nicholas12345** [noxt/DIDatepicker#16]
Hi, I added Sources to my Swift project, created bridge header. So far I failed to make DIDatepicker work, in the best case it just shows bottom red line but no dates or anything.

I had a view and view controller (UIViewController) which imports UIKit and DIDatepicker. If I use the following code below in viewDidLoad(),  I get this:
![view screenshot](http://www.dodaj.rs/f/1X/yk/3CL2lLPh/screenshot.png)

Here is a demo code:
```
let testFrame : CGRect = CGRectMake(0,200,320,100)
var testView : DIDatepickerDateView = DIDatepickerDateView(frame: testFrame)
testView.backgroundColor = UIColor(red: 0.5, green: 0.5, blue: 0.5, alpha: 1.0)
testView.alpha=0.5
self.view.addSubview(testView)
```

I tried later to add empty view in View controller and assign Class DIDatepicker from GUI. I made outlet for that view and tried to set date:
```
@IBOutlet weak var datepicker: DIDatepicker!
var todaysDate:NSDate = NSDate()
datepicker.selectDate(todaysDate)
```

But nothing happens (view stays blank). I also noticed that I can access following methods defined in DIDatepicker.h:
* selectDate
* selectDateAtIndex

But I cannot access for some reason to other ones from the list:
* fillDatesFromDate
* fillCurrentWeek
* fillCurrentMonth
* fillCurrentYear

Can you provide please some minimal Swift demo as a good starting point on how to use DIDatepicker? Does anyone have a problem with DIDatepicker? 
I use XCode 6.4, Swift 1.2, OSX Yosemite 10.10.4

Many thanks!

**Comment by allyrgb** [comment]
I'm still learning Swift, but I hope this helps. You don't need the bridging header anymore, if you specify 'use_frameworks!' in your podfile.  The IBOutlets in the following extract will obviously need to be wired to your storyboard views.  I also had to uncheck 'Use AutoLayout' to get the picker in the right place.

import UIKit
import DIDatepicker

class ViewController: UIViewController {

    
    @IBOutlet weak var datepicker: DIDatepicker!
    
    @IBOutlet weak var selectedDateLabel: UILabel!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        let startdate = NSDate()
        self.datepicker.fillCurrentYear()
        self.datepicker.selectDate(startdate)
        //self.datepicker.selectDateAtIndex(0)
        datepicker.addTarget(self, action: Selector(updateSelectedDate()), forControlEvents: UIControlEvents.ValueChanged)
        
    }

    func updateSelectedDate() {
        
        let formatter = NSDateFormatter()
        formatter.dateFormat = NSDateFormatter.dateFormatFromTemplate("EEEEddMMMM", options: 0, locale: NSLocale(localeIdentifier: "en-GB"))

        self.selectedDateLabel.text = formatter.stringFromDate(self.datepicker.selectedDate)
        
    }

**Comment by noxt** [comment]
Try my new version https://github.com/noxt/ScrollableDatepicker
