### ISSUE TITLE
Why do I have to leave some space at right to make it work?

### ISSUE THREAD

**Issue by danieltigse** [noxt/DIDatepicker#19]
<img width="311" alt="screen shot 2016-10-02 at 3 53 02 pm" src="https://cloud.githubusercontent.com/assets/1870723/19023617/669d8520-88b8-11e6-909c-86a7f4f9b3c2.png">

**Comment by noxt** [comment]
This version no longer supported. Try new version https://github.com/noxt/ScrollableDatepicker
